import { Role } from '~/types/common'

export enum Action {
  DASHBOARDS_VIEW = 'DASHBOARDS_VIEW',
  USERS_VIEW = 'USERS_VIEW',
  USERS_CREATE = 'USERS_CREATE',
  USERS_EDIT = 'USERS_EDIT',
  USERS_DELETE = 'USERS_DELETE',
  MARKETS_VIEW = 'MARKETS_VIEW',
  MARKETS_VIEW_BY_ID='MARKETS_VIEW_BY_ID',
  MARKETS_CREATE = 'MARKETS_CREATE',
  MARKETS_EDIT = 'MARKETS_EDIT',
  MARKETS_DELETE = 'MARKETS_DELETE',
  PRODUCTS_VIEW = 'PRODUCTS_VIEW',
  PRODUCTS_CREATE = 'PRODUCTS_CREATE',
  PRODUCTS_EDIT = 'PRODUCTS_EDIT',
  PRODUCTS_DELETE = 'PRODUCTS_DELETE',
  CATEGORIES_MANAGE = 'CATEGORIES_MANAGE',
  TRANSACTIONS_VIEW = 'TRANSACTIONS_VIEW',
  // Общее разрешение "создать транзакцию" — включает Seller, т.к. по бизнес-правилам
  // продавец обязан уметь оформить продажу в долг (DEBT).
  TRANSACTIONS_CREATE = 'TRANSACTIONS_CREATE',
  // Более узкое разрешение — именно обычная продажа (SALE). Seller его не получает,
  // используется в UI, чтобы не показывать продавцу тип SALE в форме создания.
  TRANSACTIONS_CREATE_SALE = 'TRANSACTIONS_CREATE_SALE',
  TRANSACTIONS_EDIT = 'TRANSACTIONS_EDIT',
  TRANSACTIONS_DELETE = 'TRANSACTIONS_DELETE',
  TRANSACTIONS_REFUND = 'TRANSACTIONS_REFUND',
  SELLERS_VIEW = 'SELLERS_VIEW',
  SELLERS_CREATE = 'SELLERS_CREATE',
  SELLERS_EDIT = 'SELLERS_EDIT',
  SELLERS_DELETE = 'SELLERS_DELETE',
  DEBTORS_VIEW = 'DEBTORS_VIEW',
  DEBTORS_CREATE = 'DEBTORS_CREATE',
  DEBTORS_EDIT = 'DEBTORS_EDIT',
  // На бэкенде DELETE /debtors/:id теперь доступен только ADMIN/OWNER —
  // Seller тут больше не должен видеть/использовать удаление.
  DEBTORS_DELETE = 'DEBTORS_DELETE',
}

export const ACTION_PERMISSIONS: Record<Action, Role[]> = {
  [Action.DASHBOARDS_VIEW]: [Role.Admin, Role.Owner, Role.Seller],
  [Action.USERS_VIEW]: [Role.Admin],
  [Action.USERS_CREATE]: [Role.Admin],
  [Action.USERS_EDIT]: [Role.Admin],
  [Action.USERS_DELETE]: [Role.Admin],
  [Action.MARKETS_VIEW]: [Role.Admin],
  [Action.MARKETS_VIEW_BY_ID]: [Role.Admin,Role.Owner],
  [Action.MARKETS_CREATE]: [Role.Admin],
  [Action.MARKETS_EDIT]: [Role.Admin],
  [Action.MARKETS_DELETE]: [Role.Admin],
  [Action.PRODUCTS_VIEW]: [Role.Admin, Role.Owner],
  [Action.PRODUCTS_CREATE]: [Role.Admin, Role.Owner],
  [Action.PRODUCTS_EDIT]: [Role.Admin, Role.Owner],
  [Action.PRODUCTS_DELETE]: [Role.Admin, Role.Owner],
  [Action.CATEGORIES_MANAGE]: [Role.Admin, Role.Owner],
  [Action.TRANSACTIONS_VIEW]: [Role.Admin, Role.Owner, Role.Seller],
  [Action.TRANSACTIONS_CREATE]: [Role.Admin, Role.Owner, Role.Seller],
  [Action.TRANSACTIONS_CREATE_SALE]: [Role.Admin, Role.Owner],
  [Action.TRANSACTIONS_EDIT]: [Role.Admin, Role.Owner],
  [Action.TRANSACTIONS_DELETE]: [Role.Admin, Role.Owner],
  [Action.TRANSACTIONS_REFUND]: [Role.Admin, Role.Owner],
  [Action.SELLERS_VIEW]: [Role.Admin, Role.Owner],
  [Action.SELLERS_CREATE]: [Role.Admin, Role.Owner],
  [Action.SELLERS_EDIT]: [Role.Admin, Role.Owner],
  [Action.SELLERS_DELETE]: [Role.Admin, Role.Owner],
  [Action.DEBTORS_VIEW]: [Role.Admin, Role.Owner, Role.Seller],
  [Action.DEBTORS_CREATE]: [Role.Admin, Role.Owner, Role.Seller],
  [Action.DEBTORS_EDIT]: [Role.Admin, Role.Owner, Role.Seller],
  [Action.DEBTORS_DELETE]: [Role.Admin, Role.Owner],
};
